name: Compute merkle roots
on:
    push:
        branches-ignore:
            - 'master'

jobs:
    run:
        name: Compute merkle roots
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install dependencies
              run: yarn install

            - name: Install dependencies
              run: yarn build

            # - name: Calculate roots for BAL
            #   run: NETWORK=homestead yarn merkle-roots --outfile ./reports/_roots.json

            - name: Calculate roots for Avax
              run: NETWORK=fuji yarn merkle-roots --outfile ./reports/_roots-fuji.json

            - name: Calculate roots for Uni
              run: NETWORK=fuji-uni yarn merkle-roots --outfile ./reports/_roots-fuji-uni.json

            - name: Calculate roots for bmock
              run: NETWORK=fuji-bmock yarn merkle-roots --outfile ./reports/_roots-fuji-bmock.json

            - name: Commit changes
              uses: EndBug/add-and-commit@v7
              with:
                  author_name: Merkle Root Bot
                  author_email: no-reply@balancer.finance
                  message: 'Computed roots for reports'
                  add: './reports/_roots*.json'
