name: Publish reports to ipfs
on:
    push:
        branches:
            - 'master'

jobs:
    ipfs-publish:
        environment: fleek
        env:
            FLEEK_API_KEY: ${{ secrets.FLEEK_API_KEY }}
            FLEEK_API_SECRET: ${{ secrets.FLEEK_API_SECRET }}
            # FLEEK_BUCKET: 'balancer-team-bucket'
            FLEEK_BUCKET: 'c11f8c76-d724-4425-8d04-b2cda29a34d5-bucket'
        name: Publish to ipfs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Set up Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: 14.x

            - name: Install dependencies
              run: yarn install

            - name: Install dependencies
              run: yarn build

            - name: Publish ipfs reports for avax on fuji
              run: NETWORK=fuji yarn ipfs-publish

            - name: Publish ipfs reports for avax on fuji-uni
              run: NETWORK=fuji-uni yarn ipfs-publish

            - name: Publish ipfs reports for avax on fuji-bmock
              run: NETWORK=fuji-bmock yarn ipfs-publish

            - name: Commit changes
              uses: EndBug/add-and-commit@v7
              with:
                  author_name: Fleek Publish Bot
                  author_email: no-reply@balancer.finance
                  branch: ipfs-publish
                  message: 'Updating ipfs links'
                  add: './reports/_current*.json'
